inventory_component/urls.py
from django.urls import path
from .import views

app_name = 'inventory_component'

urlpatterns = [
   
    path('products/',views.products_list,name ='products-list'),
    path('purchase/',views.purchase,name='purchase'),
    path('sales/',views.sales,name = "sales"), 
    path('contacts/',views.contacts,name = 'contacts')
]

main_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('inventory_component.urls')),
    path('',include('user_roles.urls'))
]
from django.conf import settings
from django.conf.urls.static import static


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_roles/urls.py
from django.urls import path,include
from .import views
app_name = 'users'

urlpatterns = [
    path('login/',views.user_login,name ='login'),
    path('users/',views.users,name ='user'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
     path('logout/', views.custom_logout, name='logout'),
]

inventory_component/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

class ProductList(models.Model):
    product_name = models.TextField()
    product_id = models.IntegerField()
    product_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.product_name

class Stock(models.Model):
    stock_name = models.TextField()
    stock_id = models.IntegerField()
    stock_quantity = models.IntegerField(default=0)
    stock_price = models.IntegerField(default=0)

    def __str__(self):
        return self.stock_name

@receiver(post_save, sender=ProductList)
def create_or_update_stock(sender, instance, created, **kwargs):
    if created:
        # If the ProductList instance is created, create the corresponding Stock instance
        Stock.objects.create(
            stock_name=instance.product_name,
            stock_id=instance.product_id,
            stock_quantity=0,
            stock_price=0
        )
    else:
        # If the ProductList instance is updated, update the corresponding Stock instance
        stock = Stock.objects.get(stock_id=instance.product_id)
        stock.stock_name = instance.product_name
        stock.save()

user_roles/models.py
# models.py

from django.db import models

class UserRolesSalesMen(models.Model):
    ROLES = (
        ('purchaser', 'Purchaser'),
        ('salesperson', 'Sales Personnel'),
    )
    
    email = models.EmailField(unique=True)
    role = models.CharField(max_length=20, choices=ROLES)

    def __str__(self):
        return self.email

inventory_component/views.py
from django.shortcuts import render,redirect
import random
from django.contrib.auth.decorators import login_required
from .models import ProductList



def products_list(request):
    products = ProductList.objects.all()
    if request.method == 'POST':
        product_name = request.POST.get('product_name')
       

        product_filter = ProductList.objects.filter(product_name=product_name)

        if product_filter:
            message = 'Item already exists'
            return render(request, 'products-list.html', {'message': message, 'products': products})

        else:
        
        
            ProductList.objects.create(
            product_name = product_name,
            product_id = random.randint(100, 999)

            )
        products = ProductList.objects.all()
        return render(request ,'products-list.html',{'products':products})

    return render(request , 'products-list.html',{'products':products})


    

def purchase(request):
    return render(request,'purchase.html')

def sales(request):
    return render(request,'sales.html')

def contacts(request):
    return render(request,'contacts.html')

user_roles/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required
from .models import UserRolesSalesMen
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.contrib.auth import logout



# Create your views here.

def user_login(request):
    if request.method == "POST":
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return render(request,"dashboard.html")
    
    else: 
        form = AuthenticationForm()
    return render(request, "login.html", { "form": form })


def users(request): 
    persons = UserRolesSalesMen.objects.all()   
    if request.method == 'POST':
        email = request.POST.get('email')
        role = request.POST.get('role')
        if email and role in ['purchaser', 'salesperson']:
            # Save the user with the specified role
            user = UserRolesSalesMen.objects.create(email=email, role=role)
            user.save()
       
        elif 'delete_email' in request.POST:
            email_to_delete = request.POST.get('delete_email')
            UserRolesSalesMen.objects.filter(email=email_to_delete).delete()

        persons = UserRolesSalesMen.objects.all()

    # Retrieve all persons
       

    return render(request, 'users.html', {'persons': persons})

   

class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard.html'


def custom_logout(request):
    logout(request)
    return redirect('../login')

inventory_component/templates/contacts.html
<!DOCTYPE html>
<!-- Designined by CodingLab | www.youtube.com/codinglabyt -->
<html lang="en" dir="ltr">
    {% load static %}
  <head>
    <meta charset="UTF-8">
    <title> Drop Down Sidebar Menu | CodingLab </title>
    <link rel="stylesheet" href={% static 'css/dashboard.css'%}>
    <!-- Boxiocns CDN Link -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
<body>
  <div class="sidebar close">
    <div class="logo-details">
      <i class="material-symbols-outlined">
        inventory_2
      </i>
      <span class="logo_name">Invento</span>
    </div>
    <ul class="nav-links">
      <li>
        <a href={% url 'users:dashboard'%}>
          <i class='bx bx-grid-alt' ></i>
          <span class="link_name">Dashboard</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href={% url 'users:dashboard'%}>Dashboard</a></li>
        </ul>
      </li>
        
      <li>
        <a href="#">
          <i class='bx bx-pie-chart-alt-2' ></i>
          <span class="link_name">Analytics</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href="#">Analytics</a></li>
        </ul>
      </li>
      <li>
        <a href= {% url 'inventory_component:products-list'%}>
          <i class="material-symbols-outlined">
            shopping_bag
          </i>
          <span class="link_name">Product List</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href= {% url 'inventory_component:products-list'%}>Product List</a></li>
        </ul>
      </li>
      <li>
        <a href={% url "inventory_component:purchase"%}>
          <i class="material-symbols-outlined">
            shopping_cart
          </i>
          <span class="link_name">Purchase</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href={% url "inventory_component:purchase"%}>Purchase</a></li>
        </ul>
      </li>
      <li>
        <a href={% url "inventory_component:sales"%}>
          <i class="material-symbols-outlined">
            sell
          </i>
          <span class="link_name">Sales</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href={% url "inventory_component:sales"%}>Sales</a></li>
        </ul>
      </li>
      <li>
        <a href="#">
          <i class="material-symbols-outlined">
            event_available
          </i>
          <span class="link_name">Stock Availability</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href="#">Stock Availability</a></li>
        </ul>
      </li>
      <li>
        <a href={% url 'users:user'%}>
          <i class="material-symbols-outlined">
            account_circle
          </i>
          <span class="link_name">Users</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href={% url 'users:user'%}>Users</a></li>
        </ul>
      </li>
      <li>
        <a href={% url 'inventory_component:contacts'%}>
          <i class="material-symbols-outlined">
            contacts
          </i>
          <span class="link_name">Contacts</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href={% url 'inventory_component:contacts'%}>Contacts</a></li>
        </ul>
      </li>
     
      
      <li>
    <div class="profile-details">
      <div class="profile-content">
        <img src="image/profile.jpg" alt="profileImg">
      </div>
      <div class="name-job">
        <div class="profile_name">{username}</div>
        <div class="job">Web Desginer</div>
      </div>
      <a href = {% url 'users:logout'%}><i class='bx bx-log-out' ></i></a>
      
      
    </div>
  </li>
</ul>
  </div>
  <section class="home-section">
    <div class="home-content">
      <i class='bx bx-menu' ></i>
      <br>
          <h1>Contacts Page</h1>
    </div>
   
  </section>

  <script src= {% static 'js/common.js'%}></script>

</body>
</html>

inventory_component/templates/dashboard.html
<!DOCTYPE html>
<!-- Designined by CodingLab | www.youtube.com/codinglabyt -->
<html lang="en" dir="ltr">
    {% load static %}
  <head>
    <meta charset="UTF-8">
    <title> Drop Down Sidebar Menu | CodingLab </title>
    <link rel="stylesheet" href={% static 'css/dashboard.css'%}>
    <!-- Boxiocns CDN Link -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
<body>
  <div class="sidebar close">
    <div class="logo-details">
      <i class="material-symbols-outlined">
        inventory_2
      </i>
      <span class="logo_name">Invento</span>
    </div>
    <ul class="nav-links">
      <li>
        <a href={% url 'users:dashboard'%}>
          <i class='bx bx-grid-alt' ></i>
          <span class="link_name">Dashboard</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href={% url 'users:dashboard'%}>Dashboard</a></li>
        </ul>
      </li>
        
      <li>
        <a href="#">
          <i class='bx bx-pie-chart-alt-2' ></i>
          <span class="link_name">Analytics</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href="#">Analytics</a></li>
        </ul>
      </li>
      <li>
        <a href= {% url 'inventory_component:products-list'%}>
          <i class="material-symbols-outlined">
            shopping_bag
          </i>
          <span class="link_name">Product List</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href= {% url 'inventory_component:products-list'%}>Product List</a></li>
        </ul>
      </li>
      <li>
        <a href={% url "inventory_component:purchase"%}>
          <i class="material-symbols-outlined">
            shopping_cart
          </i>
          <span class="link_name">Purchase</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href={% url "inventory_component:purchase"%}>Purchase</a></li>
        </ul>
      </li>
      <li>
        <a href={% url "inventory_component:sales"%}>
          <i class="material-symbols-outlined">
            sell
          </i>
          <span class="link_name">Sales</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href={% url "inventory_component:sales"%}>Sales</a></li>
        </ul>
      </li>
      <li>
        <a href="#">
          <i class="material-symbols-outlined">
            event_available
          </i>
          <span class="link_name">Stock Availability</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href="#">Stock Availability</a></li>
        </ul>
      </li>
      <li>
        <a href={% url 'users:user'%}>
          <i class="material-symbols-outlined">
            account_circle
          </i>
          <span class="link_name">Users</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href={% url 'users:user'%}>Users</a></li>
        </ul>
      </li>
      <li>
        <a href={% url 'inventory_component:contacts'%}>
          <i class="material-symbols-outlined">
            contacts
          </i>
          <span class="link_name">Contacts</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href={% url 'inventory_component:contacts'%}>Contacts</a></li>
        </ul>
      </li>
     
      
      <li>
    <div class="profile-details">
      <div class="profile-content">
        <img src="image/profile.jpg" alt="profileImg">
      </div>
      <div class="name-job">
        <div class="profile_name">{username}</div>
        <div class="job">Web Desginer</div>
      </div>
      <a href = {% url 'users:logout'%}><i class='bx bx-log-out' ></i></a>
      
      
    </div>
  </li>
</ul>
  </div>
  <section class="home-section">
    <div class="home-content">
      <i class='bx bx-menu' ></i>
          
    </div>
    <div class = "dashboard">
        <div class = "element">
            <a href = {% url 'inventory_component:purchase'%}><h1>Total Purchase</h1>
            <h2 class = "amount">400</h2></a>
        </div>
        <div class = "element">
           <a href = {% url "inventory_component:sales"%}> <h1>Total Sales</h1>
            <h2 class = "amount">412</h2></a>
        </div>
        
      
    </div>
    <div class = "dashboard">
         <div class = "element">
            <a href = {}><h1>Stocks Available</h1>
            <h2 class = "amount">100</h2></a>
        </div>
    
        <div class = "element">
           <a href = {}> <h1>Revenue</h1>
            <h2 class = "amount">Rs.50,000</h2></a>
        </div>
        
      
    </div>
    <div class = "products-list">
        <a href = {% url 'inventory_component:products-list'%}><h1>Total Products Listed</h1>
        <h2>38</h2></a>
    </div>
  </section>

  <script src= {% static 'js/common.js'%}></script>

</body>
</html>

inventory_component/templates/products-list.html
<!DOCTYPE html>
<!-- Designined by CodingLab | www.youtube.com/codinglabyt -->
<html lang="en" dir="ltr">
    {% load static %}
  <head>
    <meta charset="UTF-8">
    <title> Drop Down Sidebar Menu | CodingLab </title>
    <link rel="stylesheet" href={% static 'css/dashboard.css'%}>
    <link rel="stylesheet" href={% static 'css/products-list.css'%}>
    <!-- Boxiocns CDN Link -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
<body>
  <div class="sidebar close">
    <div class="logo-details">
      <i class="material-symbols-outlined">
        inventory_2
      </i>
      <span class="logo_name">Invento</span>
    </div>
    <ul class="nav-links">
      <li>
        <a href={% url 'users:dashboard'%}>
          <i class='bx bx-grid-alt' ></i>
          <span class="link_name">Dashboard</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href={% url 'users:dashboard'%}>Dashboard</a></li>
        </ul>
      </li>
        
      <li>
        <a href="#">
          <i class='bx bx-pie-chart-alt-2' ></i>
          <span class="link_name">Analytics</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href="#">Analytics</a></li>
        </ul>
      </li>
      <li>
        <a href= {% url 'inventory_component:products-list'%}>
          <i class="material-symbols-outlined">
            shopping_bag
          </i>
          <span class="link_name">Product List</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href= {% url 'inventory_component:products-list'%}>Product List</a></li>
        </ul>
      </li>
      <li>
        <a href={% url 'inventory_component:purchase'%}>
          <i class="material-symbols-outlined">
            shopping_cart
          </i>
          <span class="link_name">Purchase</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href={% url 'inventory_component:purchase'%}>Purchase</a></li>
        </ul>
      </li>
      <li>
        <a href={% url "inventory_component:sales"%}>
          <i class="material-symbols-outlined">
            sell
          </i>
          <span class="link_name">Sales</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href={% url "inventory_component:sales"%}>Sales</a></li>
        </ul>
      </li>
      <li>
        <a href="#">
          <i class="material-symbols-outlined">
            event_available
          </i>
          <span class="link_name">Stock Availability</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href="#">Stock Availability</a></li>
        </ul>
      </li>
     
      
      <li>
    <div class="profile-details">
      <div class="profile-content">
        <img src="image/profile.jpg" alt="profileImg">
      </div>
      <div class="name-job">
        <div class="profile_name">{username}</div>
        <div class="job">Web Desginer</div>
      </div>
      <i class='bx bx-log-out' ></i>
    </div>
  </li>
</ul>
  </div>
  <section class="home-section">
    <div class="home-content">
      <i class='bx bx-menu' ></i>
          
    </div>
  <div class = "list">
        <h1>List of Products : </h1>
  </div>
  <button type = "submit" class = "submit-btn" id ="openModalBtn" style = "cursor:pointer">Add + </button>
  <table class = "product" bgcolor = "#11101d">
    <tr class = "row" bgcolor="#E4E9F7">
        <th class = "colummn">Product Id</th>
        <th class = "colummn">Product Name</th>
        <th class = "colummn">Added Date</th>
    </tr>
    {% for product in products %}
    <tr class = "row">
        <td class = "colummn">{{product.product_id}}</th>
        <td class = "colummn">{{product.product_name}}</th>
        <td class = "colummn">{{product.product_date}}</th>
    </tr>
   {% endfor %}
    
      
        
     
  </table>

  <div id="modal" class="modal">
    <div class="modal-content">
      <span class="close">&times;</span><br>
      <h2>Enter the Product you want to List:</h2>
      <br>
      <form method = "post">
        {% csrf_token %}
        <input type="text" class="input" placeholder="Enter something..." name = 'product_name'>
        {% if message %}
    <p>{{ message }}</p>
          {% endif %}
        <button type = "submit" class = "submit-btn ">Submit</button>
      </form>
     
    </div>
  </div>


  

  
  </section>

  <script src= {% static 'js/common.js'%}></script>
  <script src= {% static 'js/script.js'%}></script>

</body>
</html>

inventory_component/templates/purchase.html
<!DOCTYPE html>
<!-- Designined by CodingLab | www.youtube.com/codinglabyt -->
<html lang="en" dir="ltr">
    {% load static %}
  <head>
    <meta charset="UTF-8">
    <title> Drop Down Sidebar Menu | CodingLab </title>
    <link rel="stylesheet" href={% static 'css/dashboard.css'%}>
    <link rel="stylesheet" href= {% static "css/purchase.css" %}>
    <!-- Boxiocns CDN Link -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
<body>
  <div class="sidebar close">
    <div class="logo-details">
      <i class="material-symbols-outlined">
        inventory_2
      </i>
      <span class="logo_name">Invento</span>
    </div>
    <ul class="nav-links">
      <li>
        <a href="{% url 'users:dashboard'%}">
          <i class='bx bx-grid-alt' ></i>
          <span class="link_name">Dashboard</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href={% url 'users:dashboard'%}>Dashboard</a></li>
        </ul>
      </li>
        
      <li>
        <a href="#">
          <i class='bx bx-pie-chart-alt-2' ></i>
          <span class="link_name">Analytics</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href="#">Analytics</a></li>
        </ul>
      </li>
      <li>
        <a href={% url 'inventory_component:products-list'%}>
          <i class="material-symbols-outlined">
            shopping_bag
          </i>
          <span class="link_name">Product List</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href="{% url 'inventory_component:products-list'%}">Product List</a></li>
        </ul>
      </li>
      <li>
        <a href={% url 'inventory_component:purchase'%}>
          <i class="material-symbols-outlined">
            shopping_cart
          </i>
          <span class="link_name">Purchase</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href={% url 'inventory_component:purchase'%}>Purchase</a></li>
        </ul>
      </li>
      <li>
        <a href={% url "inventory_component:sales"%}>
          <i class="material-symbols-outlined">
            sell
          </i>
          <span class="link_name">Sales</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href={% url "inventory_component:sales"%}>Sales</a></li>
        </ul>
      </li>
      <li>
        <a href="#">
          <i class="material-symbols-outlined">
            event_available
          </i>
          <span class="link_name">Stock Availability</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href="#">Stock Availability</a></li>
        </ul>
      </li>
      <li>
        <a href={% url 'users:user'%}>
          <i class="material-symbols-outlined">
            account_circle
          </i>
          <span class="link_name">Users</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href={% url 'users:user'%}>Users</a></li>
        </ul>
      </li>
     
      
      <li>
    <div class="profile-details">
      <div class="profile-content">
        <img src="image/profile.jpg" alt="profileImg">
      </div>
      <div class="name-job">
        <div class="profile_name">{username}</div>
        <div class="job">Web Desginer</div>
      </div>
      <i class='bx bx-log-out' ></i>
    </div>
  </li>
</ul>
  </div>
  <section class="home-section">
    <div class="home-content">
      <i class='bx bx-menu' ></i>
          
    </div>
    <br>
    <div class = "revenvue-box">
      <h1>Welcome to Purchase Portal ! </h1>
    </div>

    <div class = "search-bar">
        <input type="text" placeholder="Search..">
    </div>

    <button type = "submit" class = "submit-btn" id ="openModalBtn">Buy</button>
    <div class = "purchase">
        
        
            <table class = "purchase-table">
                <tr class = "row">
                    <th class="column">Product ID</th>
                    <th class="column">Name</th>
                    <th class="column">Quantity</th>
                   
                    <th class="column">Total Price</th>
                   
                    <th class="column">Seller Number</th>
                    <th class="column">Location</th>
                </tr>
                <tr class = "row">
                    <td class="column">201</td>
                    <td class="column">Vatiska</td>
                    <td class="column">40</td>
                    
                    <td class="column">400</td>
                    
                    <td class="column">9023891021</td>
                    <td class="column">Warehouse 1 </td>
                </tr>
            </table>
            <div id="modal" class="modal">
              <div class="modal-content">
                <span class="close">&times;</span><br>
                <form method = "post">
                  {% csrf_token %}
                  <h1>Pro ID:</h1>
                  <input type = "text" name = "pro-id" class = "pro-input">
                  <h1>Product Name:</h1>
                  <input type = "text" name = "pro-name" class = "pro-input">
                  <h1>Ouantity:</h1>
                  <input type = "text" name = "quantity" class = "pro-input">
                  <h1>Price Per Item:</h1>
                  <input type = "number" name = "pro-ppi" class = "pro-input">
                  <h1>Total Price:</h1>
                  <input type = "number" name = "pro-total" class = "pro-input">
                  <h1>Seller Name:</h1>
                  <input type = "text" name = "pro-seller" class = "pro-input">
                  <h1>Seller Phone Number:</h1>
                  <input type = "number" name = "pro-seller-num" class = "pro-input"><br>
                  <h1>Location:</h1>
                  <input type = "text" name = "pro-location" class = "pro-input"><br>

                  <button type = "submit" class = "pro-submit">Submit</button>
                </form>
              </div>
            </div>
            
        

  </section>


  <script src= {% static 'js/common.js'%}></script>
  <script src= {% static 'js/script.js'%}></script>

</body>
</html>

user_roles/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel = "stylesheet" href = {% static "css/login.css" %}>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
</head>
<body>
    <div class = "login-container">
        
        <div class = "img-login"><i class="material-symbols-outlined">
            inventory_2
          </i>
          <span class="logo_name">Invento</span><img src={% static '../media/login1.jpg' %} alt="login image"></div>
    <div>
    <form class="sign-in" action="/login/" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="submit-btn">Submit</button>


    </form>
    
</div>
</div>
</body>
</html>